"""Versioned Extension SDK for tools, Skills, Capability Packs, and artifacts."""

from harness_core.artifact_views import (
    ArtifactView,
    ArtifactViewAction,
    ArtifactViewField,
    project_artifact_view,
    project_artifact_views,
)
from harness_core.capabilities import (
    ArtifactTypeSpec,
    CapabilityCatalog,
    CapabilityContribution,
    CapabilityInstallContext,
    CapabilityPack,
    CapabilityPackSpec,
    capability_pack_spec,
)
from harness_core.clarifications import (
    ClarificationRequest,
    clarification_from_validation_error,
    clarification_tool_result,
)
from harness_core.conformance import (
    CapabilityPackConformanceReport,
    validate_capability_pack,
)
from harness_core.handoffs import (
    HandoffRegistry,
    HandoffSpec,
    standardize_pending_action_payload,
)
from harness_core.prompts import harness_system_prompt
from harness_core.references import (
    DefaultReferenceProjector,
    EvidenceBundle,
    ReferenceProjection,
    ReferenceProjector,
)
from harness_core.skill_packages import (
    ArtifactPresentationActionSpec,
    ArtifactPresentationFieldSpec,
    ArtifactPresentationSpec,
    CompiledSkillSpec,
    SkillPackageManifest,
    load_skill_packages,
    validate_skill_packages,
)
from harness_core.skill_activation import (
    EntryToolActivationDecision,
    EntryToolActivationRequest,
    EntryToolSkillActivator,
)
from harness_core.tool_registry import ToolRegistry, ToolSpec
from harness_core.tool_disclosure import (
    TOOL_DISCOVERY_NAME,
    LexicalToolDiscovery,
    ToolDescriptor,
    ToolDiscoveryPort,
    ToolView,
    discover_tools,
    install_tool_discovery,
    resolve_tool_view,
    tool_discovery_spec,
)
from harness_core.capability_manifest import (
    CapabilityManifest,
    RuntimeGeneration,
    RuntimeGenerationManager,
    load_capability_manifest,
    validate_manifest_set,
)
from harness_core.capability_control import (
    CapabilityPackageConflict,
    CapabilityPackageManager,
    CapabilityPackageRecord,
    CapabilityPackageSnapshot,
    CapabilityPackageStore,
    InMemoryCapabilityPackageStore,
)
from harness_core.hooks import (
    HookAction,
    HookAudit,
    HookDecision,
    HookExecutionError,
    HookExecutionStore,
    HookInvocation,
    HookPoint,
    HookRunResult,
    HookRunner,
    HookScope,
    HookSpec,
    InMemoryHookExecutionStore,
)
from harness_core.tool_providers import ToolProvider, ToolProviderSpec, verify_tool_provider
from harness_core.tools import (
    ToolExecutionClaim,
    ToolExecutionContext,
    ToolExecutionStore,
    ToolExecutor,
    ToolHandler,
    ToolPreflight,
)

EXTENSION_SDK_API = (
    "ArtifactPresentationActionSpec",
    "ArtifactPresentationFieldSpec",
    "ArtifactPresentationSpec",
    "ArtifactTypeSpec",
    "ArtifactView",
    "ArtifactViewAction",
    "ArtifactViewField",
    "CapabilityCatalog",
    "CapabilityContribution",
    "CapabilityInstallContext",
    "CapabilityManifest",
    "CapabilityPack",
    "CapabilityPackConformanceReport",
    "CapabilityPackSpec",
    "CapabilityPackageConflict",
    "CapabilityPackageManager",
    "CapabilityPackageRecord",
    "CapabilityPackageSnapshot",
    "CapabilityPackageStore",
    "ClarificationRequest",
    "CompiledSkillSpec",
    "DefaultReferenceProjector",
    "EvidenceBundle",
    "EntryToolActivationDecision",
    "EntryToolActivationRequest",
    "EntryToolSkillActivator",
    "HandoffRegistry",
    "HandoffSpec",
    "HookAction",
    "HookAudit",
    "HookDecision",
    "HookExecutionError",
    "HookExecutionStore",
    "HookInvocation",
    "HookPoint",
    "HookRunResult",
    "HookRunner",
    "HookScope",
    "HookSpec",
    "InMemoryHookExecutionStore",
    "InMemoryCapabilityPackageStore",
    "ReferenceProjection",
    "ReferenceProjector",
    "RuntimeGeneration",
    "RuntimeGenerationManager",
    "SkillPackageManifest",
    "ToolExecutionClaim",
    "ToolExecutionContext",
    "ToolExecutionStore",
    "ToolExecutor",
    "ToolHandler",
    "ToolProvider",
    "ToolProviderSpec",
    "ToolPreflight",
    "ToolRegistry",
    "ToolSpec",
    "TOOL_DISCOVERY_NAME",
    "LexicalToolDiscovery",
    "ToolDescriptor",
    "ToolDiscoveryPort",
    "ToolView",
    "capability_pack_spec",
    "clarification_from_validation_error",
    "clarification_tool_result",
    "discover_tools",
    "harness_system_prompt",
    "install_tool_discovery",
    "load_skill_packages",
    "load_capability_manifest",
    "standardize_pending_action_payload",
    "project_artifact_view",
    "project_artifact_views",
    "resolve_tool_view",
    "tool_discovery_spec",
    "validate_capability_pack",
    "validate_skill_packages",
    "validate_manifest_set",
    "verify_tool_provider",
)

__all__ = list(EXTENSION_SDK_API)
