"""Versioned Extension SDK for tools, Skills, Capability Packs, and artifacts."""

from deepkeel.capabilities import (
    ArtifactTypeSpec,
    CapabilityCatalog,
    CapabilityContribution,
    CapabilityInstallContext,
    CapabilityPack,
    CapabilityPackSpec,
    capability_pack_spec_from_manifest,
    capability_pack_spec,
)
from deepkeel.clarifications import (
    ClarificationRequest,
    clarification_from_validation_error,
    clarification_tool_result,
)
from deepkeel.entrypoints import (
    AgentEntrypointSpec,
)
from deepkeel.conformance import (
    CapabilityLifecycleConformanceReport,
    CapabilityPackageCertificationReport,
    CapabilityPackConformanceReport,
    REQUIRED_CAPABILITY_EVAL_TAGS,
    certify_capability_package,
    validate_capability_pack,
)
from deepkeel.handoffs import (
    HandoffRegistry,
    HandoffSpec,
    standardize_pending_action_payload,
)
from deepkeel.prompts import harness_system_prompt
from deepkeel.references import (
    DefaultReferenceProjector,
    ReferenceProjection,
    ReferenceProjector,
)
from deepkeel.skill_packages import (
    ArtifactPresentationActionSpec,
    ArtifactPresentationFieldSpec,
    ArtifactPresentationSpec,
    CompiledSkillSpec,
    SkillPackageManifest,
    load_skill_packages,
    validate_skill_packages,
)
from deepkeel.skill_activation import (
    EntryToolActivationDecision,
    EntryToolActivationRequest,
    EntryToolSkillActivator,
)
from deepkeel.skill_disclosure import (
    SKILL_DISCOVERY_NAME,
    LexicalSkillDiscovery,
    LexicalSkillReranker,
    SkillDescriptor,
    SkillDiscoveryPort,
    SkillRerankerPort,
    discover_skills,
    install_skill_discovery,
    skill_discovery_spec,
)
from deepkeel.tool_registry import ToolRegistry, ToolSpec
from deepkeel.tool_disclosure import (
    TOOL_DISCOVERY_NAME,
    LexicalToolDiscovery,
    LexicalToolReranker,
    ToolDescriptor,
    ToolDiscoveryPort,
    ToolRerankerPort,
    ToolView,
    discover_tools,
    install_tool_discovery,
    resolve_tool_view,
    tool_discovery_spec,
)
from deepkeel.capability_manifest import (
    CapabilityBudgetSpec,
    CapabilityManifest,
    RuntimeGeneration,
    RuntimeGenerationManager,
    load_capability_manifest,
    validate_manifest_set,
)
from deepkeel.capability_control import (
    CapabilityPackageConflict,
    CapabilityPackageManager,
    CapabilityPackageRecord,
    CapabilityPackageSnapshot,
    CapabilityPackageStore,
    InMemoryCapabilityPackageStore,
)
from deepkeel.hooks import (
    HookAction,
    HookAudit,
    HookDecision,
    HookExecutionError,
    HookExecutionStore,
    HookInvocation,
    HookPoint,
    HookRunResult,
    HookRunner,
    HookScope,
    HookSpec,
    InMemoryHookExecutionStore,
)
from deepkeel.tool_providers import ToolProvider, ToolProviderSpec, verify_tool_provider
from deepkeel.tools import (
    ToolExecutionClaim,
    ToolExecutionContext,
    ToolExecutionStore,
    ToolExecutor,
    ToolHandler,
    ToolPreflight,
)
from deepkeel.async_ports import (
    AsyncToolExecutionStore,
    AsyncToolExecutionStoreAdapter,
)

EXTENSION_SDK_API = (
    "AgentEntrypointSpec",
    "AsyncToolExecutionStore",
    "AsyncToolExecutionStoreAdapter",
    "ArtifactPresentationActionSpec",
    "ArtifactPresentationFieldSpec",
    "ArtifactPresentationSpec",
    "ArtifactTypeSpec",
    "CapabilityCatalog",
    "CapabilityBudgetSpec",
    "CapabilityContribution",
    "CapabilityInstallContext",
    "CapabilityManifest",
    "CapabilityLifecycleConformanceReport",
    "CapabilityPack",
    "CapabilityPackageCertificationReport",
    "CapabilityPackConformanceReport",
    "CapabilityPackSpec",
    "CapabilityPackageConflict",
    "CapabilityPackageManager",
    "CapabilityPackageRecord",
    "CapabilityPackageSnapshot",
    "CapabilityPackageStore",
    "ClarificationRequest",
    "CompiledSkillSpec",
    "DefaultReferenceProjector",
    "EntryToolActivationDecision",
    "EntryToolActivationRequest",
    "EntryToolSkillActivator",
    "HandoffRegistry",
    "HandoffSpec",
    "HookAction",
    "HookAudit",
    "HookDecision",
    "HookExecutionError",
    "HookExecutionStore",
    "HookInvocation",
    "HookPoint",
    "HookRunResult",
    "HookRunner",
    "HookScope",
    "HookSpec",
    "InMemoryHookExecutionStore",
    "InMemoryCapabilityPackageStore",
    "ReferenceProjection",
    "ReferenceProjector",
    "REQUIRED_CAPABILITY_EVAL_TAGS",
    "RuntimeGeneration",
    "RuntimeGenerationManager",
    "SkillPackageManifest",
    "SKILL_DISCOVERY_NAME",
    "LexicalSkillDiscovery",
    "LexicalSkillReranker",
    "SkillDescriptor",
    "SkillDiscoveryPort",
    "SkillRerankerPort",
    "ToolExecutionClaim",
    "ToolExecutionContext",
    "ToolExecutionStore",
    "ToolExecutor",
    "ToolHandler",
    "ToolProvider",
    "ToolProviderSpec",
    "ToolPreflight",
    "ToolRegistry",
    "ToolSpec",
    "TOOL_DISCOVERY_NAME",
    "LexicalToolDiscovery",
    "LexicalToolReranker",
    "ToolDescriptor",
    "ToolDiscoveryPort",
    "ToolRerankerPort",
    "ToolView",
    "capability_pack_spec",
    "capability_pack_spec_from_manifest",
    "certify_capability_package",
    "clarification_from_validation_error",
    "clarification_tool_result",
    "discover_tools",
    "discover_skills",
    "harness_system_prompt",
    "install_tool_discovery",
    "install_skill_discovery",
    "load_skill_packages",
    "load_capability_manifest",
    "standardize_pending_action_payload",
    "resolve_tool_view",
    "tool_discovery_spec",
    "skill_discovery_spec",
    "validate_capability_pack",
    "validate_skill_packages",
    "validate_manifest_set",
    "verify_tool_provider",
)

__all__ = list(EXTENSION_SDK_API)
