"""Versioned Runtime SDK for executing, observing, and recovering runs."""

from deepkeel.artifact_views import (
    ArtifactView,
    ArtifactViewAction,
    ArtifactViewField,
    project_artifact_view,
    project_artifact_views,
)
from deepkeel.contracts import (
    AgentMessage,
    Artifact,
    FinalAnswer,
    MessageContentPart,
    Observation,
    PendingAction,
    RunContext,
    RunStatus,
    TaskLifecycle,
    RuntimeEvent,
    ToolCall,
    ToolResult,
)
from deepkeel.context_snapshot import (
    context_snapshot_subject,
    normalize_agent_context_snapshot,
)
from deepkeel.control import (
    CancellableRunControl,
    InMemoryRunControl,
    NoopRunControl,
    RunControl,
)
from deepkeel.composition import HarnessRuntimeBuilder, RuntimeProfile, RuntimeProfileName
from deepkeel.evaluation import (
    EvalCase,
    EvalCaseResult,
    EvalExpectation,
    EvalSuiteReport,
    EvalSuiteRunner,
    EvalViolation,
    evaluate_runtime_result,
)
from deepkeel.events import AgentEventPersistenceError, normalize_runtime_event
from deepkeel.entrypoints import (
    CapabilityView,
    narrow_capability_view,
    resolve_capability_view,
)
from deepkeel.failures import (
    FailureDiagnosis,
    RunCanceledError,
    diagnose_failure,
    failure_from_code,
)
from deepkeel.persistence import DurableCheckpointStore, InMemoryDurableCheckpointStore
from deepkeel.recovery import RecoveryOutcome, RecoveryState, classify_recovery_outcome
from deepkeel.operations import (
    InMemoryRunRecoveryExecutor,
    RunInspection,
    RunOperationReceipt,
    RunOperations,
    RunOperationsUnavailable,
    RunRecoveryAction,
    RunRecoveryCommand,
    RunRecoveryExecutor,
)
from deepkeel.runtime import HarnessRuntime
from deepkeel.runtime_api import (
    RuntimeActiveTask,
    RuntimeErrorPayload,
    RuntimeEventEnvelope,
    RuntimeReference,
    RuntimeRequest,
    RuntimeResult,
    RuntimeResultStatus,
    RuntimeStreamEvent,
    RuntimeUIState,
)
from deepkeel.scope import (
    RuntimeScope,
    RuntimeScopeUnsupported,
    resolve_runtime_scope,
)
from deepkeel.state_store import (
    InMemoryRuntimeStateStore,
    QueryableRuntimeStateStore,
    RUN_SETTLED_EVENT,
    RunAggregate,
    RunStateSnapshot,
    RuntimeStateConflict,
    RuntimeStateMutation,
    RuntimeStateReceipt,
    RuntimeStateStore,
    ScopedRuntimeStateStore,
    TERMINAL_RUN_STATUSES,
    normalize_runtime_status,
)
from deepkeel.ui import (
    TERMINAL_RUNTIME_STATUSES,
    project_run_ui_state,
    task_lifecycle,
)
from deepkeel.references import EvidenceBundle
from deepkeel.version import (
    EVENT_SCHEMA_VERSION,
    DEEPKEEL_CONTRACT_VERSION,
    DEEPKEEL_VERSION,
    PACKAGE_VERSION,
    RUNTIME_CONTRACT_VERSION,
    SDK_API_VERSION,
)
from deepkeel.workflows import TERMINAL_WORKFLOW_STATES, workflow_projection

RUNTIME_SDK_API = (
    "AgentEventPersistenceError",
    "AgentMessage",
    "Artifact",
    "ArtifactView",
    "ArtifactViewAction",
    "ArtifactViewField",
    "CancellableRunControl",
    "CapabilityView",
    "DurableCheckpointStore",
    "EvalCase",
    "EvalCaseResult",
    "EvalExpectation",
    "EvalSuiteReport",
    "EvalSuiteRunner",
    "EvalViolation",
    "EvidenceBundle",
    "EVENT_SCHEMA_VERSION",
    "FailureDiagnosis",
    "FinalAnswer",
    "DEEPKEEL_CONTRACT_VERSION",
    "DEEPKEEL_VERSION",
    "PACKAGE_VERSION",
    "HarnessRuntime",
    "HarnessRuntimeBuilder",
    "InMemoryRunControl",
    "InMemoryRunRecoveryExecutor",
    "InMemoryDurableCheckpointStore",
    "InMemoryRuntimeStateStore",
    "MessageContentPart",
    "NoopRunControl",
    "Observation",
    "PendingAction",
    "QueryableRuntimeStateStore",
    "RecoveryOutcome",
    "RecoveryState",
    "RunCanceledError",
    "RunInspection",
    "RunOperationReceipt",
    "RunOperations",
    "RunOperationsUnavailable",
    "RunRecoveryAction",
    "RunRecoveryCommand",
    "RunRecoveryExecutor",
    "RUN_SETTLED_EVENT",
    "RunAggregate",
    "RunContext",
    "RunControl",
    "RunStatus",
    "TaskLifecycle",
    "RunStateSnapshot",
    "RuntimeEvent",
    "RuntimeActiveTask",
    "RuntimeErrorPayload",
    "RuntimeEventEnvelope",
    "RuntimeReference",
    "RuntimeRequest",
    "RuntimeProfile",
    "RuntimeProfileName",
    "RuntimeResult",
    "RuntimeResultStatus",
    "RUNTIME_CONTRACT_VERSION",
    "RuntimeScope",
    "RuntimeScopeUnsupported",
    "RuntimeStateConflict",
    "RuntimeStateMutation",
    "RuntimeStateReceipt",
    "RuntimeStateStore",
    "ScopedRuntimeStateStore",
    "RuntimeStreamEvent",
    "RuntimeUIState",
    "SDK_API_VERSION",
    "TERMINAL_RUNTIME_STATUSES",
    "TERMINAL_RUN_STATUSES",
    "TERMINAL_WORKFLOW_STATES",
    "ToolCall",
    "ToolResult",
    "context_snapshot_subject",
    "classify_recovery_outcome",
    "diagnose_failure",
    "failure_from_code",
    "evaluate_runtime_result",
    "normalize_agent_context_snapshot",
    "normalize_runtime_event",
    "normalize_runtime_status",
    "narrow_capability_view",
    "project_run_ui_state",
    "project_artifact_view",
    "project_artifact_views",
    "task_lifecycle",
    "resolve_runtime_scope",
    "resolve_capability_view",
    "workflow_projection",
)

__all__ = list(RUNTIME_SDK_API)
